### ISSUE TITLE
Error: Cannot find module 'react-jsonschema-form'

### ISSUE THREAD

**Issue by tisto** [plone/plone-react#2]
1) Checkout repo
2) Run "yarn install"
3) Run "yarn start":

```$ yarn start
yarn start v0.19.1
$ NODE_ENV=production npm-run-all run:prod:server
yarn run v0.19.1
$ better-npm-run run_prod_server
running better-npm-run in /Users/timo/workspace/plone/plone-react
Executing script: run_prod_server

to be executed: ./node_modules/.bin/babel-node ./src/start-server-prod.js


Error: Cannot find module 'react-jsonschema-form'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (/Users/timo/workspace/plone/plone-react/static/dist/server.js:6754:19)
    at __webpack_require__ (/Users/timo/workspace/plone/plone-react/static/dist/server.js:519:30)
    at fn (/Users/timo/workspace/plone/plone-react/static/dist/server.js:50:20)
    at Object.<anonymous> (/Users/timo/workspace/plone/plone-react/static/dist/server.js:6621:29)
    at __webpack_require__ (/Users/timo/workspace/plone/plone-react/static/dist/server.js:519:30)
    at fn (/Users/timo/workspace/plone/plone-react/static/dist/server.js:50:20)
    at Object.module.exports.Object.defineProperty.value (/Users/timo/workspace/plone/plone-react/static/dist/server.js:1591:15)
    at __webpack_require__ (/Users/timo/workspace/plone/plone-react/static/dist/server.js:519:30)
    at fn (/Users/timo/workspace/plone/plone-react/static/dist/server.js:50:20)
    at Object.<anonymous> (/Users/timo/workspace/plone/plone-react/static/dist/server.js:1425:21)
    at __webpack_require__ (/Users/timo/workspace/plone/plone-react/static/dist/server.js:519:30)
    at fn (/Users/timo/workspace/plone/plone-react/static/dist/server.js:50:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "run:prod:server" exited with 1.
error Command failed with exit code 1.
Timos-MBP:plone-react timo$```

**Comment by robgietema** [comment]
@tisto Are you still having this issue on master? `react-jsonschema-form` is not used anymore and there are no references in the code anymore.

**Comment by tisto** [comment]
Strange. Even removing node_modules did not help. I had to do a fresh git checkout. Now the problem is gone...
